# -*- coding: utf-8 -*-
"""Processo conhecido como Data Wrangling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18SFxQ4OTqv3Qg19CWWVi7IdHBINW1IHM

# **Processo conhecido como Data Wrangling**

Abrir um arquivo CSV no **Colab Research Google**, você pode seguir os seguintes passos:

*Primeiro, faça o upload do arquivo CSV para o seu ambiente do Colab Research. Você pode fazer isso clicando no ícone "Arquivos" na barra lateral esquerda e, em seguida, clicando no botão "Fazer upload" na parte inferior do painel.

Segundo, depois de fazer o upload do arquivo CSV, você pode carregá-lo em um DataFrame do Pandas usando o seguinte código:*
"""

import pandas as pd
df = pd.read_csv('/content/despesa_ceaps_2022.csv',encoding="ISO-8859-1")

df.head()

"""Verificando informação do dataset, arquivo: despesa_ceaps_2022.csv
Com os comandos:

---


<df.shape> = *Por exemplo, se você tiver um DataFrame chamado "df" com 100 linhas e 5 colunas, o comando "df.shape" retornará a tupla (100, 5).*

<df.columns> = *O comando df.columns é usado para retornar os rótulos das colunas de um objeto DataFrame do Pandas. Ele retorna um objeto Index que contém os rótulos das colunas do DataFrame*

"""

df.shape

df.columns

df['COD_DOCUMENTO'].nunique()

df.isnull().any(axis=1)

linhas_com_nulos = df[df.isnull().any(axis=1)]
linhas_com_nulos

df.isnull().sum()

df['DOCUMENTO'].fillna('SEM COMPROVAÇÃO DE DOCUMENTO', inplace=True)

df['DETALHAMENTO'].fillna('SEM DETALHAMENTO DE DOCUMENTO', inplace=True)

df.isnull().sum()

dados_sem_comprovacao = df.loc[(df['DOCUMENTO'] == 'SEM COMPROVAÇÃO DE DOCUMENTO') & (df['DETALHAMENTO'] == 'SEM DETALHAMENTO DE DOCUMENTO')]
dados_sem_comprovacao

numero_de_dados_sem_comprovacao = dados_sem_comprovacao.shape[0]

numero_de_dados_sem_comprovacao

df.to_csv('/content/despesas_ceaps_2022_atualizado.csv', index=False)

df_atualizado = pd.read_csv('/content/despesas_ceaps_2022_atualizado.csv', encoding="ISO-8859-1")

df_atualizado.head()

df.isnull().isnull().sum()

dados_sem_comprovacao.to_csv('/content/despesa_ceaps_2022_sem_comprovacao.csv', columns=df.columns, index=False)

df_sem_comprovacao = pd.read_csv('/content/despesa_ceaps_2022_sem_comprovacao.csv', encoding="ISO-8859-1")
df_sem_comprovacao